### ISSUE TITLE
'Uniprot_acc' not found using SnpSift with dbNSFPv3.0b1a

### ISSUE THREAD

**Issue by gpcr** [pcingola/SnpSift#26]
Hi @pcingola 

When trying to annotate using SnpSift against local dbNSFP3.0.gz (dbNSFPv3.0b1a version) 

Error: 'Uniprot_acc' field not found:  I checked the data indeed not found ....how can SnpSift can ignore this?

Thanks for your support

00:00:00.000    SnpSift version 4.1h (build 2015-08-03), by Pablo Cingolani
00:00:00.006    Command: 'DBNSFP'
00:00:00.007    Reading configuration file 'snpEff.config'
00:00:00.315    done
00:00:00.316    Annotating
        Input file    : 'test.vcf'
        Database file : '/data4/snpEff/data/dbNSFP3.0.gz'
00:00:00.442    Guessing data types
.................................00:00:11.737   Done
Error: Error: Field name 'Uniprot_acc' not found

**Comment by pcingola** [comment]
Thank you for the heads up!
I've just uploaded a fixed version (4.1 I release 2015-08-14), it should solve the problem.
