### ISSUE TITLE
escaping () in extractFields

### ISSUE THREAD

**Issue by asalomatov** [pcingola/SnpSift#29]
Hi,

my vcf file has an info field named dbNSFP_pos(1-coor). When I try to extract it with extractFields it causes unknown function exception. How to escape parenthesis?

Thanks.

**Comment by asalomatov** [comment]
as a work around i renamed it with sed, is there a better way?

**Comment by pcingola** [comment]
Yes, sed is the best workaround. 
I'm puzzled on why you want to annotate the position, since you already have that information in the 'POS' column in your VCF file...

**Comment by asalomatov** [comment]
thanks... you're right to be puzzled, no good reason for extracting pos, was taking all fields by default.
