### ISSUE TITLE
FILTER for '*' or '?' constraint for more than 1 variable not supported

### ISSUE THREAD

**Issue by mitochon** [pcingola/SnpSift#38]
**Problem**
FILTER expression involving '*' or '?' does not give correct result if more than 1 variable used.

Example:
query Q1 => filter "(BAR[\*] < 0.1)" test.vcf -> yields no result
query Q2 => filter "(BAR[\*] < 0.1) & (FOO[\*] >= 2)" test.vcf -> yields 3 result
Q2 is more strict than Q1 so its result should always be a subset of Q1's result.

------
Hi I discovered the above problem some time back and submitted a pull request
(https://github.com/pcingola/SnpSift/pull/37)

Please let me know if this is the proper channel for submitting patches.
Thanks.

** Currently there's a merge conflict (minor issue due to test cases numbering). Once the PR is reviewed, I can incorporate feedback / rebase and resolve the conflicts.

**Comment by pcingola** [comment]
Hi,
   I'll take a look at it as soon as I get back in town. Apologies for not
merging before.
   Yours

   Pablo
