### ISSUE TITLE
SnpSift gwasCat added vcf header to the end of the vcf file

### ISSUE THREAD

**Issue by hou** [pcingola/SnpSift#42]
SnpSift version 4.3t (build 2017-11-24 10:18)

When I tried to annotate my vcf using the gwas catalog, I found out that SnpSift gwasCat added the VCF header to the end of the my file.

**Comment by LenaObeid** [comment]
Hi,
I've run into the same problem with SnpSift version 5.0. After annotation with SnpSift gwasCat, VCF header is at the beginning as well as at the end of VCF.

**Comment by chunxuan-hs** [comment]
Same problem here, any ideas?
