### ISSUE TITLE
SNPSIFT extractFields

### ISSUE THREAD

**Issue by rtemanni** [pcingola/SnpSift#43]
Hi 
Would it be possible to add another parameter to `SNPSIFT extractFields -ff FieldsFile` to be able to pass fields as a text file (one field by line)? 
Eventually, it will be great if two columns are provided in the file the second column will be the name of the column for that field.
Thanks

**Comment by cbrueffer** [comment]
:+1: but both those features would be great!

**Comment by AroobAlhumaidy** [comment]
good suggestion
