### ISSUE TITLE
SnpSift extractFields ANN[0].RANK 

### ISSUE THREAD

**Issue by zzupmc** [pcingola/SnpSift#46]
Hi, 

I have a vcf file annotated by snpeff and want to extract "ANN[*].RANK" from the ANN field like 

`ANN=G|missense_variant|MODERATE|TNN|ENSG00000120332|transcript|ENST00000239462|protein_coding|13/19|c.3038C>G|p.Thr1013Arg|3151/5008|3038/3900|1013/1299||`

I used snpsift version 4.3t with the following command 

`java -jar /home/pmi/src/snpEff/SnpSift.jar extractFields -e "." my.vcf CHROM POS ID REF ALT "ANN[*].RANK" `

but I got 13 not 13/19 for ANN[*].RANK. 

thanks,
Hongen

**Comment by AlesMaver** [comment]
I have the same problem, did you perhaps find the solution? Thanks!

**Comment by SophiaMurat** [comment]
Hello,
I have the same problem. Has anyone found a solution?
Thanks,
Sophia
