### ISSUE TITLE
line 1:11 no viable alternative at input '[*].GENE:'

### ISSUE THREAD

**Issue by AroobAlhumaidy** [pcingola/SnpSift#53]
Hello, 
i followed the instructions on this page https://pcingola.github.io/SnpEff/ss_extractfields/  in order to use extractfields to separate annotations in separate columns.. I used this command: 

$ cat my.ann1.vcf     | /mnt/e/Bioinformatics/tools/snpeff/snpEff/scripts/vcfEffOnePerLine.pl     | java -jar /mnt/e/Bioinformatics/tools/snpeff/snpEff/SnpSift.jar extractFields - CHROM POS REF ALT QUAL DP ANN "ANN[*].ALLELE" "ANN[*].EFFECT" "ANN[*].IMPACT:" "ANN[*].GENE:" "ANN[*].GENEID:" ANN[*].FEATURE" "ANN[*].FEATUREID" "ANN[*].BIOTYPE:" "ANN[*].RANK:" "ANN[*].HGVS_C" "ANN[*].HGVS_P" "ANN[*].CDNA_POS" "ANN[*].CDNA_LEN" "ANN[*].CDS_POS" "ANN[*].CDS_LEN" "ANN[*].AA_POS" "ANN[*].AA_LEN" "ANN[*].DISTANCE" "ANN[*].ERRORS"  > snpsiftout8.vcf \ 

I faced 2 issues: 
1- the code hanged at > sign, for longer time than expected
2- I tried to shorten the parameters in order to see where is the hang, by using: 
$ cat my.ann.vcf | /mnt/e/Bioinformatics/tools/snpeff/snpEff/scripts/vcfEffOnePerLine.pl     |java -jar /mnt/e/Bioinformatics/tools/snpeff/snpEff/SnpSift.jar  extractFields - CHROM POS REF ALT QUAL DP "ANN[*].ALLELE" "ANN[*].EFFECT" "ANN[*].GENE:" "ANN[*].GENEID:"  > snpsiftout2.vcf

then I got: 
line 1:11 no viable alternative at input '[*].GENE:'
line 1:13 no viable alternative at input '[*].GENEID:'

I appreciate any insights, 

Thanks 
![Capture1](https://user-images.githubusercontent.com/39539904/100226448-d3022180-2f30-11eb-8e65-d79ada1ce137.PNG)

**Comment by aknfa** [comment]
Did you fix your problem? I encountered the same output.

**Comment by aknfa** [comment]
I found what was an issue. You need to remove colons (:) from the script. So it should turn to "ANN[*].IMPACT" from "ANN[*].IMPACT:"

**Comment by AroobAlhumaidy** [comment]
yes it's solved, i used this command: 

$ cat my.ann.vcf | /e/Bioinformatics/tools/snpeff/scripts/vcfEffOnePerLine.pl | java -jar /e/Bioinformatics/tools/snpeff/SnpSift.jar  extractFields - CHROM POS ID REF ALT QUAL DP FILTER "ANN[*].ALLELE" "ANN[*].GENE" "ANN[*].EFFECT" "ANN[*].HGVS_P" "ANN[*].FEATURE" "ANN[*].FEATUREID"   "ANN[*].HGVS_C"  "ANN[*].CDNA_POS" "ANN[*].CDNA_LEN" "ANN[*].CDS_POS" "ANN[*].CDS_LEN" "ANN[*].AA_POS" "ANN[*].AA_LEN" "ANN[*].DISTANCE" "ANN[*].ERRORS" "ANN[*].GENEID" "ANN[*].BIOTYPE" "ANN[*].RANK"  > snpsiftout.vcf
