### ISSUE TITLE
dbNSFPv4.1a database does not index using tabix

### ISSUE THREAD

**Issue by kgandh2** [pcingola/SnpSift#54]
Hi there - I have downloaded dbNSFPv4.1a from the website and am trying to create a database for snpSift to use. I followed the instructions on this page. 
https://pcingola.github.io/SnpEff/ss_dbnsfp/

However, tabix is not able to index the file and throws error below
[get_intv] the following line cannot be parsed and skipped: Binary file (standard input) matches
[ti_index_core] the indexes overlap or are out of bounds

It appears like there are multiple records for one genomic position for different alternate alleles. I have tried to sort the file, check for empty lines and check for complete duplicate lines. 

Please help. 

Thank you,
Kuki

**Comment by pcingola** [comment]
The file from that page (see "Database" section) is already indexed, the tabix index file should be downloaded alongside the original dbNSFP file (you have to download two files).
