### ISSUE TITLE
How to escape special characters in SnpSift filter query string?

### ISSUE THREAD

**Issue by marcora** [pcingola/SnpSift#56]
I am trying to filter on a field with round parentheses in its name but I cannot figure out what character to use to escape them in the SnpSift filter query string.

**Comment by pcingola** [comment]
Can you show an example of the VCF line with the identifier?
I'm not even sure if parenthesis are allowed in identifiers.

**Comment by marcora** [comment]
chr9    12316   .       T       C       129.72  VQSRTrancheSNP99.95to100.00

AC=3;AF=0.0004843;AN=4054;BaseQRankSum=1.73;DP=68011;ExcessHet=3.1948;FS=118.363;InbreedingCoeff=-0.0751;MLEAC=12;MLEAF=0.0004151;MQ=25.29;MQRankSum=-1.32;QD=0.96;ReadPosRankSum=-0.48;SOR=4.031;VQSLOD=-192.5;culprit=FS;VFLAGS_ADSP_Discovery-Nimblegen_VCRome_V2.1=1,3,4,11;ABHet_ADSP_Discovery-Nimblegen_VCRome_V2.1=NA;VariantType=SNV;VFLAGS_ADSP_Discovery-Illumina_Rapid_Capture_Exome_(ICE)_kit=1,3,4,11;ABHet_ADSP_Discovery-Illumina_Rapid_Capture_Exome_(ICE)_kit=NA;VFLAGS_ADGC_AA-Agilent_WES_v6_capture_region=1,3,4;ABHet_ADGC_AA-Agilent_WES_v6_capture_region=NA;VFLAGS_FASe_Families-Agilent_WES_v5_capture_region=1,2,3,4,11;ABHet_FASe_Families-Agilent_WES_v5_capture_region=NA;VFLAGS_FASe_Families-Nimblegen_VCRome_sequencing_w-Custom_Spike-In_Baits=1,3,4,11;ABHet_FASe_Families-Nimblegen_VCRome_sequencing_w-Custom_Spike-In_Baits=NA;VFLAGS_FASe_Families-Nimblegen_VCRome_V2.1=1,2,3,4,11;ABHet_FASe_Families-Nimblegen_VCRome_V2.1=NA;VFLAGS_Brkanac_Families-Roche_SeqCap_EZ_Exome_Probes_v2.0_Target_Enrichment_Probes=1,2,3,4,11;ABHet_Brkanac_Families-Roche_SeqCap_EZ_Exome_Probes_v2.0_Target_Enrichment_Probes=NA;VFLAGS_Miami_Families-Agilent_WES_v3_capture_region=1,2,3,4,11;ABHet_Miami_Families-Agilent_WES_v3_capture_region=NA;VFLAGS_Miami_Families-Agilent_WES_v4_capture_region=1,2,3,4,11;ABHet_Miami_Families-Agilent_WES_v4_capture_region=NA;VFLAGS_Columbia_WHICAP-Roche_SeqCap_EZ_Exome_Probes_v3.0_Target_Enrichment_Probes=1,4,11;ABHet_Columbia_WHICAP-Roche_SeqCap_EZ_Exome_Probes_v3.0_Target_Enrichment_Probes=0.7941;VFLAGS_KnightADRC-Nimblegen_VCRome_sequencing_w-Custom_Spike-In_Baits=1,3,4,11;ABHet_KnightADRC-Nimblegen_VCRome_sequencing_w-Custom_Spike-In_Baits=NA;VFLAGS_KnightADRC-IDT_xGen_Exome_Whole_Exome_Research_Panel_v1.0_w-Custom_Spike-In_Baits=1,2,3,4,11;ABHet_KnightADRC-IDT_xGen_Exome_Whole_Exome_Research_Panel_v1.0_w-Custom_Spike-In_Baits=NA;VFLAGS_CBD-Agilent_WES_v5_capture_region=1,2,3,4,11;ABHet_CBD-Agilent_WES_v5_capture_region=NA;VFLAGS_PSP-Nimblegen_VCRome_V2.1=1,2,3,4,11;ABHet_PSP-Nimblegen_VCRome_V2.1=NA;VariantInTargetFraction=3157/20650;VariantInTargetRatio=0.152881

**Comment by marcora** [comment]
SnpSift chokes on round parentheses and period characters.

**Comment by pcingola** [comment]
Apologies but the information you provide is still rather incomplete and I'm unable to reproduce the error condition.
- What is the exact command line you are trying to run?
- What are the inputs to the command?
- What is the error message?
- Which SnpEff version are you using?

The snippet you posted doesn't look like a valid VCF file, so it makes sense that SnpSift will reject it. Maybe it didn't copy properly on the Github issue. Can you attach (instead of trying to copy-paste) the VCF file? I don't need to the full VCF, just a few lines to reproduce the error.

Here are some guidelines on how to report a bug: https://pcingola.github.io/SnpEff/about/#bug-reports
