### ISSUE TITLE
how to download dbSNP142.vcf file?

### ISSUE THREAD

**Issue by ketkijoshi278** [pcingola/SnpSift#59]
Can anyone please send me the link to download dbSNP142.vcf file to be used to annotate my .vcf files.
I have a dbSNP142 file but its extension is .txt and not .vcf.

**Comment by pcingola** [comment]
dbNSP's home is here: https://www.ncbi.nlm.nih.gov/snp/ (you can Google "dbSNP" and it's probably the first link).
Follow the download link from there.
You don't need version 142, it's better to download the latest version (I think as of today, it's 155).
