### ISSUE TITLE
Missing 'chr' columns in dbNSFP file

### ISSUE THREAD

**Issue by shangyf-stu** [pcingola/SnpSift#60]
Dear sir or madam,
I am sorry to interrupt you. 
When I was using snpSift v3.6 to run a pipeline, I encountered an error.
`Exception in thread "main" java.lang.RuntimeException: Missing 'chr' columns in dbNSFP file
	at ca.mcgill.mcb.pcingola.fileIterator.DbNsfpFileIterator.parseHeader(DbNsfpFileIterator.java:382)
	at ca.mcgill.mcb.pcingola.fileIterator.DbNsfpFileIterator.getFieldNames(DbNsfpFileIterator.java:143)
	at ca.mcgill.mcb.pcingola.snpSift.SnpSiftCmdDbNsfp.checkFieldsToAdd(SnpSiftCmdDbNsfp.java:158)
	at ca.mcgill.mcb.pcingola.snpSift.SnpSiftCmdDbNsfp.run(SnpSiftCmdDbNsfp.java:362)
	at ca.mcgill.mcb.pcingola.snpSift.SnpSift.run(SnpSift.java:233)
	at ca.mcgill.mcb.pcingola.snpSift.SnpSift.main(SnpSift.java:60)`

The version of dbNSFP is 3.3a.
The first line of the dbNSFP file is
`#Chr,Start,End,Ref,Alt,SIFT_score,SIFT_converted_rankscore,SIFT_pred,Polyphen2_HDIV_score,Polyphen2_HDIV_rankscore,Polyphen2_HDIV_pred,Polyphen2_HVAR_score,Polyphen2_HVAR_rankscore,Polyphen2_HVAR_pred,LRT_score,LRT_converted_rankscore,LRT_pred,MutationTaster_score,MutationTaster_converted_rankscore,MutationTaster_pred,MutationAssessor_score,MutationAssessor_score_rankscore,MutationAssessor_pred,FATHMM_score,FATHMM_converted_rankscore,FATHMM_pred,PROVEAN_score,PROVEAN_converted_rankscore,PROVEAN_pred,VEST3_score,VEST3_rankscore,MetaSVM_score,MetaSVM_rankscore,MetaSVM_pred,MetaLR_score,MetaLR_rankscore,MetaLR_pred,M-CAP_score,M-CAP_rankscore,M-CAP_pred,CADD_raw,CADD_raw_rankscore,CADD_phred,DANN_score,DANN_rankscore,fathmm-MKL_coding_score,fathmm-MKL_coding_rankscore,fathmm-MKL_coding_pred,Eigen_coding_or_noncoding,Eigen-raw,Eigen-PC-raw,GenoCanyon_score,GenoCanyon_score_rankscore,integrated_fitCons_score,integrated_fitCons_score_rankscore,integrated_confidence_value,GERP++_RS,GERP++_RS_rankscore,phyloP100way_vertebrate,phyloP100way_vertebrate_rankscore,phyloP20way_mammalian,phyloP20way_mammalian_rankscore,phastCons100way_vertebrate,phastCons100way_vertebrate_rankscore,phastCons20way_mammalian,phastCons20way_mammalian_rankscore,SiPhy_29way_logOdds,SiPhy_29way_logOdds_rankscore,Interpro_domain,GTEx_V6_gene,GTEx_V6_tissue`

Hope you can give me some suggestions or help, thank you very much！！

**Comment by pcingola** [comment]
Are you using the latest SnpSift version?
Have you downloaded the latest dbNSFP and index files from the documentation's link (https://pcingola.github.io/SnpEff/ss_dbnsfp/)?
